from __future__ import annotations

from pathlib import Path

from gateway.pdf_reports import REPORTS_DIR, generate_pdf_report


def test_generate_pdf_report_handles_bullet_analysis() -> None:
    result = generate_pdf_report({
        "title": "May Performance",
        "theme": "light",
        "sections": [
            {
                "type": "analysis",
                "title": "Financial Analysis & Insights",
                "content": "• Revenue Activity: May MTD revenue of AED 11.85M\n• Cost Management: Expense control improved",
            },
            {
                "type": "comparison_chart",
                "title": "Revenue Performance Comparison",
                "data": [
                    {"period": "April 2026", "revenue": 24562346.77, "expenses": 21846112.49, "profit": 2716234.28},
                    {"period": "May 2026 (MTD)", "revenue": 11851889.97, "expenses": 3688140.61, "profit": 8163749.36},
                ],
            },
            {
                "type": "footer",
                "content": "Generated by Elrace ERP System | Confidential Financial Data | May 14, 2026",
            },
        ],
    })

    assert "error" not in result
    pdf_path = REPORTS_DIR / Path(result["pdf_url"]).name
    assert pdf_path.exists()
    assert result["size_bytes"] > 0


def test_generate_pdf_report_writes_minimal_spec() -> None:
    result = generate_pdf_report({
        "title": "May Performance",
        "theme": "light",
        "sections": [],
    })

    assert "error" not in result
    pdf_path = REPORTS_DIR / Path(result["pdf_url"]).name
    assert pdf_path.exists()
    assert result["size_bytes"] > 1200


def test_generate_pdf_report_writes_file_and_preview() -> None:
    result = generate_pdf_report({
        "title": "April Performance",
        "subtitle": "Elrace Cos.",
        "theme": "light",
        "language": "en",
        "sections": [
            {"type": "cover", "title": "April Performance", "content": "Executive summary"},
            {
                "type": "bar_chart",
                "title": "Revenue by Client",
                "data": {
                    "labels": ["A", "B"],
                    "values": [1000, 2500],
                },
            },
            {
                "type": "table",
                "title": "Totals",
                "data": {
                    "headers": ["Metric", "Value"],
                    "rows": [["Revenue", 3500]],
                },
            },
        ],
    })

    pdf_path = REPORTS_DIR / Path(result["pdf_url"]).name
    assert pdf_path.exists()
    assert result["size_bytes"] > 0
    assert result["page_count"] >= 1
    if result.get("preview_image"):
        preview_path = REPORTS_DIR / Path(result["preview_image"]).name
        assert preview_path.exists()
