#!/usr/bin/env python3
"""Render monitoring/alertmanager/alertmanager.generated.yml from .env (Phase 6)."""
from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "monitoring" / "alertmanager" / "alertmanager.generated.yml"


def _truthy(name: str) -> bool:
    return os.environ.get(name, "").strip().lower() in ("1", "true", "yes")


def _yaml_email_block(indent: str, to_addrs: str) -> str:
    host = os.environ.get("ALERT_EMAIL_SMTP_HOST", "smtp.gmail.com:587")
    from_addr = os.environ.get("ALERT_EMAIL_FROM", "ooa-alerts@localhost")
    username = os.environ.get("ALERT_EMAIL_USERNAME", "")
    password = os.environ.get("ALERT_EMAIL_PASSWORD", "")
    auth = ""
    if username and password:
        auth = f"""
{indent}  auth_username: '{username}'
{indent}  auth_password: '{password}'"""
    return f"""
{indent}email_configs:
{indent}  - to: '{to_addrs}'
{indent}    from: '{from_addr}'
{indent}    smarthost: '{host}'
{indent}    send_resolved: true{auth}
"""


def _yaml_slack_block(indent: str, channel: str) -> str:
    url = os.environ.get("ALERT_SLACK_WEBHOOK_URL", "").strip()
    if not url:
        return ""
    return f"""
{indent}slack_configs:
{indent}  - api_url: '{url}'
{indent}    channel: '{channel}'
{indent}    send_resolved: true
{indent}    title: '{{{{ template "slack.default.title" . }}}}'
{indent}    text: '{{{{ template "slack.default.text" . }}}}'
"""


def main() -> int:
    try:
        from dotenv import load_dotenv

        load_dotenv(ROOT / ".env")
    except ImportError:
        pass

    email_on = _truthy("ALERT_EMAIL_ENABLED")
    slack_on = _truthy("ALERT_SLACK_ENABLED") and bool(
        os.environ.get("ALERT_SLACK_WEBHOOK_URL", "").strip()
    )

    default_to = os.environ.get("ALERT_EMAIL_TO", "admin@example.com")
    critical_to = os.environ.get("ALERT_CRITICAL_EMAIL_TO", default_to)
    slack_ch = os.environ.get("ALERT_SLACK_CHANNEL", "#ooa-alerts")
    slack_crit = os.environ.get("ALERT_SLACK_CRITICAL_CHANNEL", "#ooa-alerts-critical")

    default_receiver = "  - name: default\n"
    if email_on:
        default_receiver += _yaml_email_block("  ", default_to)
    elif slack_on:
        default_receiver += _yaml_slack_block("  ", slack_ch)

    critical_receiver = "  - name: critical-alerts\n"
    high_receiver = "  - name: high-alerts\n"
    if email_on:
        critical_receiver += _yaml_email_block("  ", critical_to)
        high_receiver += _yaml_email_block("  ", default_to)
    if slack_on:
        critical_receiver += _yaml_slack_block("  ", slack_crit)
        high_receiver += _yaml_slack_block("  ", slack_ch)

    if not email_on and not slack_on:
        critical_receiver += "    # Enable ALERT_EMAIL_ENABLED or ALERT_SLACK_ENABLED in .env\n"
        high_receiver += "    # Enable ALERT_EMAIL_ENABLED or ALERT_SLACK_ENABLED in .env\n"

    yaml = f"""# Generated by scripts/render_alertmanager_config.py — do not edit by hand
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: default
  routes:
    - matchers:
        - severity="critical"
      receiver: critical-alerts
      continue: true
    - matchers:
        - severity=~"high|warning"
      receiver: high-alerts

receivers:
{default_receiver}
{critical_receiver}
{high_receiver}
inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity=~"warning|medium|high"
    equal: ['alertname']
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(yaml, encoding="utf-8")
    print(f"Wrote {OUT}")
    if not email_on and not slack_on:
        print(
            "Note: no email/Slack receivers enabled — alerts visible in Grafana/Prometheus only.",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
