"""Execute Visualize agent tools."""

from __future__ import annotations

import logging
from typing import Any

from visualize.brain import run_inspection, run_pattern_analysis, run_recommendation
from visualize.data_resolver import (
    collect_tables_from_items,
    enrich_pdf_sections,
    resolve_table_from_visualization,
)
from visualize.excel_generator import generate_excel_workbook
from visualize.pdf_generator import generate_visualize_pdf
from visualize.sessions import VisualizeSession, update_session

logger = logging.getLogger(__name__)

def execute_visualize_tool(
    tool_name: str,
    tool_input: dict[str, Any],
    session: VisualizeSession,
) -> dict[str, Any]:
    if tool_name == "inspect_data":
        items = tool_input.get("dropped_items") or session.dropped_items
        return {"inspection": run_inspection(items)}

    if tool_name == "analyze_patterns":
        items = session.dropped_items
        inspection = tool_input.get("inspection") or run_inspection(items)
        analysis = run_pattern_analysis(items, inspection)
        return {"inspection": inspection, "analysis": analysis}

    if tool_name == "recommend_format":
        inspection = tool_input.get("inspection") or run_inspection(session.dropped_items)
        analysis = tool_input.get("analysis") or run_pattern_analysis(
            session.dropped_items, inspection
        )
        return {
            "recommendation": run_recommendation(inspection, analysis),
        }

    if tool_name == "generate_pdf":
        spec = {
            "title": tool_input.get("title") or "Elrace Report",
            "subtitle": tool_input.get("subtitle"),
            "date_range": tool_input.get("date_range"),
            "language": tool_input.get("language", "en"),
            "theme": tool_input.get("theme"),
            "visualize_theme": tool_input.get("theme"),
            "layout": tool_input.get("layout"),
            "include_logo": tool_input.get("include_logo", True),
            "page_numbers": tool_input.get("page_numbers", True),
            "watermark": tool_input.get("watermark"),
            "logo_url": tool_input.get("logo_url"),
            "sections": tool_input.get("sections") or [],
        }
        if not spec["sections"]:
            spec["sections"] = _fallback_sections_from_items(session.dropped_items, spec["title"])
        else:
            spec["sections"] = enrich_pdf_sections(spec["sections"], session.dropped_items)
        result = generate_visualize_pdf(spec, session_id=session.session_id)
        if "error" not in result:
            update_session(
                session.session_id,
                output_type="pdf",
                theme=tool_input.get("theme"),
                layout=tool_input.get("layout"),
                last_output=result,
            )
        return result

    if tool_name == "generate_excel":
        result = generate_excel_workbook(
            {
                **tool_input,
                "data_context": _data_context_from_items(session.dropped_items),
            },
            session_id=session.session_id,
        )
        if "error" not in result:
            update_session(session.session_id, output_type="excel", last_output=result)
        return result

    if tool_name == "refine_output":
        note = tool_input.get("refinement_request", "")
        update_session(session.session_id, last_output={
            **(session.last_output or {}),
            "refinement_pending": note,
        })
        return {
            "acknowledged": True,
            "refinement_request": note,
            "message": "Noted. Describe the change and I will regenerate.",
        }

    return {"error": "unknown_tool", "message": f"Unknown tool: {tool_name}"}


def _fallback_sections_from_items(items: list[dict[str, Any]], title: str) -> list[dict[str, Any]]:
    sections: list[dict[str, Any]] = [
        {"type": "cover", "title": title, "content": "Generated by Visualize Agent"},
    ]
    for item in items:
        question = (item.get("question") or "").strip()
        text = (item.get("text") or "").strip()
        if question:
            sections.append({
                "type": "section_header",
                "title": question[:120],
            })
        if text:
            sections.append({
                "type": "executive_summary",
                "title": "Summary",
                "content": text[:8000],
            })
        viz = item.get("visualization")
        if not isinstance(viz, dict):
            continue
        table = resolve_table_from_visualization(viz)
        if table.get("rows"):
            sections.append({
                "type": "table",
                "title": table.get("title") or viz.get("title") or "Data",
                "data": {
                    "headers": table.get("headers") or [],
                    "rows": table.get("rows") or [],
                },
            })
    return sections


def _data_context_from_items(items: list[dict[str, Any]]) -> dict[str, Any]:
    tables = collect_tables_from_items(items)
    if tables:
        first = tables[0]
        return {
            "headers": first.get("headers") or [],
            "rows": first.get("rows") or [],
        }
    for item in items:
        viz = item.get("visualization")
        if isinstance(viz, dict) and isinstance(viz.get("data"), dict):
            table = resolve_table_from_visualization(viz)
            if table.get("rows"):
                return {
                    "headers": table.get("headers") or [],
                    "rows": table.get("rows") or [],
                }
            return viz["data"]
    return {}
